# Project
version=0.2.0
group=sircow.roomfortwo
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Room For Two
mod_author=Sir_Cow
mod_id=roomfortwo
license=MIT
credits=Contributors: ChaosTheLegend, LokiLeiche
description=Lets you share a bed with a villager or another player.
minecraft_version_range=1.20.1

# Forge
forge_version=47.4.20
forge_loader_version_range=[46,48)
forge_version_range=[46,48)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false
