# Project
version=0.2.0
group=sircow.roomfortwo
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Room For Two
mod_author=Sir_Cow
mod_id=roomfortwo
license=MIT
credits=Contributors: ChaosTheLegend, LokiLeiche
description=Lets you share a bed with a villager or another player.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.154.0+26.1.2
fabric_loader_version=0.19.3
modmenu_version=18.0.0-beta.1

# Forge
forge_version=64.0.11
forge_loader_version_range=[62,)

# NeoForge
neoforge_version=26.1.2.78
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false
