# Project
version=0.2.0
group=sircow.roomfortwo
java_version=17

# Common
minecraft_version=1.18.2
mod_name=Room For Two
mod_author=Sir_Cow
mod_id=roomfortwo
license=MIT
credits=Contributors: ChaosTheLegend, LokiLeiche
description=Lets you share a bed with a villager or another player.
minecraft_version_range=1.18.2

# Forge
forge_version=40.3.12
forge_loader_version_range=[40,41)
forge_version_range=[40,41)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false